[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
    'spark-spells/=lib/spark-spells/src/',
    'xchain-helpers/=lib/xchain-helpers/src/'
]

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
